let isoCodes = {
    'AH': 'AF',
    'AB': 'AL',
    'AL': 'DZ',
    'AS': 'AS',
    'AD': 'AD',
    'AN': 'AO',
    'A1': 'AI',
    'AA': 'AQ',
    'AT': 'AG',
    'AG': 'AR',
    'AM': 'AM',
    'AW': 'AW',
    'AU': 'AU',
    'AU': 'AU',
    'OS': 'AT',
    'A2': 'AZ',
    'BS': 'BS',
    'BN': 'BH',
    'BW': 'BD',
    'BR': 'BB',
    'BY': 'BY',
    'BX': 'BE',
    'BH': 'BZ',
    'BJ': 'BJ',
    'BE': 'BM',
    'B2': 'BT',
    'BO': 'BO',
    'BA': 'BA',
    'BC': 'BW',
    'BV': 'BV',
    'BZ': 'BR',
    'BT': 'IO',
    'BF': 'BN',
    'BU': 'BG',
    'HV': 'BF',
    'BI': 'BI',
    'KH': 'KH',
    'CM': 'CM',
    'CA': 'CA',
    'CV': 'CV',
    'GC': 'KY',
    'CE': 'CF',
    'CD': 'TD',
    'CH': 'CL',
    'CI': 'CN',
    'CX': 'CX',
    'CC': 'CC',
    'CO': 'CO',
    'IC': 'KM',
    'CG': 'CG',
    'CD': 'CD',
    'KU': 'CK',
    'CS': 'CR',
    'IV': 'CI',
    'RH': 'HR',
    'CU': 'CU',
    'CY': 'CY',
    'CZ': 'CZ',
    'DN': 'DK',
    'DJ': 'DJ',
    'DO': 'DM',
    'DR': 'DO',
    'EQ': 'EC',
    'EG': 'EG',
    'ES': 'SV',
    'GQ': 'GQ',
    'E1': 'ER',
    'EE': 'EE',
    'ET': 'ET',
    'FK': 'FK',
    'FA': 'FO',
    'FJ': 'FJ',
    'FI': 'FI',
    'FR': 'FR',
    'FG': 'GF',
    'PF': 'PF',
    'TF': 'TF',
    'GO': 'GA',
    'GB': 'GM',
    'GE': 'GE',
    'DL': 'DE',
    'GH': 'GH',
    'GI': 'GI',
    'GR': 'GR',
    'GL': 'GL',
    'GD': 'GD',
    'GP': 'GP',
    'GU': 'GU',
    'GU': 'GT',
    'GN': 'GN',
    'GW': 'GW',
    'GY': 'GY',
    'HA': 'HT',
    'HM': 'HM',
    'VA': 'VA',
    'HO': 'HN',
    'HK': 'HK',
    'HU': 'HU',
    'IL': 'IS',
    'IN': 'IN',
    'ID': 'ID',
    'IR': 'IR',
    'IQ': 'IQ',
    'IE': 'IE',
    'IS': 'IL',
    'IY': 'IT',
    'JM': 'JM',
    'JP': 'JP',
    'JD': 'JO',
    'KZ': 'KZ',
    'KN': 'KE',
    'KB': 'KI',
    'KR': 'KP',
    'KO': 'KR',
    'KW': 'KW',
    'KG': 'KG',
    'LA': 'LA',
    'LV': 'LV',
    'LB': 'LB',
    'LS': 'LS',
    'LI': 'LR',
    'LY': 'LY',
    'LT': 'LI',
    'L1': 'LT',
    'LU': 'LU',
    'MU': 'MO',
    'MK': 'MK',
    'MG': 'MG',
    'MW': 'MW',
    'MS': 'MY',
    'MV': 'MV',
    'MI': 'ML',
    'ML': 'MT',
    'MH': 'MH',
    'MP': 'MP',
    'MR': 'MQ',
    'MT': 'MR',
    'MA': 'MU',
    'YT': 'YT',
    'MX': 'MX',
    'US_FM': 'FM',
    'M1': 'MD',
    'M3': 'MC',
    'MO': 'MN',
    'M2': 'MS',
    'MC': 'MA',
    'MZ': 'MZ',
    'BM': 'MM',
    'NM': 'NA',
    'NW': 'NR',
    'NP': 'NP',
    'NL': 'NL',
    'AN': 'AN',
    'NZ': 'NZ',
    'NC': 'NC',
    'NK': 'NI',
    'NR': 'NE',
    'NI': 'NG',
    'N1': 'NU',
    'XX_NF': 'NF',
    'US_MP': 'MP',
    'NO': 'NO',
    'OM': 'OM',
    'PK': 'PK',
    'PW': 'PW',
    'PS': 'PS',
    'PM': 'PA',
    'NG': 'PG',
    'PY': 'PY',
    'PR': 'PE',
    'PH': 'PH',
    'P2': 'PN',
    'PL': 'PL',
    'PO': 'PT',
    'PR': 'PR',
    'QT': 'QA',
    'RE': 'RE',
    'RO': 'RO',
    'RS': 'RU',
    'RW': 'RW',
    'HE': 'SH',
    'K1': 'KN',
    'LC': 'LC',
    'P1': 'PM',
    'VC': 'VC',
    'ZM': 'WS',
    'SM': 'SM',
    'TP': 'ST',
    'SD': 'SA',
    'SG': 'SN',
    'SC': 'SC',
    'SL': 'SL',
    'SR': 'SG',
    'S1': 'SK',
    'LJ': 'SI',
    'SO': 'SB',
    'SI': 'SO',
    'ZA': 'ZA',
    'GS': 'GS',
    'SP': 'ES',
    'SB': 'LK',
    'SS': 'SS',
    'SU': 'SD',
    'SM': 'SR',
    'SJ': 'SJ',
    'SV': 'SZ',
    'SN': 'SE',
    'SW': 'CH',
    'SY': 'SY',
    'TW': 'TW',
    'TJ': 'TJ',
    'TN': 'TZ',
    'TH': 'TH',
    'EA': 'TL',
    'TG': 'TG',
    'TK': 'TK',
    'TO': 'TO',
    'TD': 'TT',
    'TS': 'TN',
    'TU': 'TR',
    'TM': 'TM',
    'TI': 'TC',
    'TV': 'TV',
    'TB': 'TB',
    'UG': 'UG',
    'UR': 'UA',
    'ER': 'AE',
    'UK': 'GB',
    'US': 'US',
    'US_UM': 'UM',
    'UY': 'UY',
    'UZ': 'UZ',
    'NH': 'VU',
    'VN': 'VE',
    'VS': 'VN',
    'VG': 'VG',
    'VI': 'VI',
    'FW': 'WF',
    'EH': 'EH',
    'YE': 'YE',
    'RB': 'RS',
    'KV': 'KV',
    'M4': 'ME',
    'ZB': 'ZM',
    'ZW': 'ZW'
};

let countryNames = {
    'AF': 'Afghanistan',
    'AX': 'Åland Islands',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AS': 'American Samoa',
    'AD': 'Andorra',
    'AO': 'Angola',
    'AI': 'Anguilla',
    'AQ': 'Antarctica',
    'AG': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AW': 'Aruba',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BS': 'Bahamas',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BB': 'Barbados',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BZ': 'Belize',
    'BJ': 'Benin',
    'BM': 'Bermuda',
    'BT': 'Bhutan',
    'BO': 'Bolivia (Plurinational State of)',
    'BQ': 'Bonaire, Sint Eustatius and Saba',
    'BA': 'Bosnia and Herzegovina',
    'BW': 'Botswana',
    'BV': 'Bouvet Island',
    'BR': 'Brazil',
    'IO': 'British Indian Ocean Territory',
    'BN': 'Brunei Darussalam',
    'BG': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'CV': 'Cabo Verde',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'KY': 'Cayman Islands',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'CX': 'Christmas Island',
    'CC': 'Cocos (Keeling) Islands',
    'CO': 'Colombia',
    'KM': 'Comoros',
    'CG': 'Congo',
    'CD': 'Congo (Democratic Republic of the)',
    'CK': 'Cook Islands',
    'CR': 'Costa Rica',
    'CI': 'Côte d\'Ivoire',
    'HR': 'Croatia',
    'CU': 'Cuba',
    'CW': 'Curaçao',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'DJ': 'Djibouti',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'SV': 'El Salvador',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'ET': 'Ethiopia',
    'FK': 'Falkland Islands (Malvinas)',
    'FO': 'Faroe Islands',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'GF': 'French Guiana',
    'PF': 'French Polynesia',
    'TF': 'French Southern Territories',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GR': 'Greece',
    'GL': 'Greenland',
    'GD': 'Grenada',
    'GP': 'Guadeloupe',
    'GU': 'Guam',
    'GT': 'Guatemala',
    'GG': 'Guernsey',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HT': 'Haiti',
    'HM': 'Heard Island and McDonald Islands',
    'VA': 'Holy See',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran (Islamic Republic of)',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IM': 'Isle of Man',
    'IL': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'JE': 'Jersey',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'KP': 'Korea (Democratic People\'s Republic of)',
    'KR': 'Korea (Republic of)',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Lao People\'s Democratic Republic',
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MO': 'Macao',
    'MK': 'Macedonia (the former Yugoslav Republic of)',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'MH': 'Marshall Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'YT': 'Mayotte',
    'MX': 'Mexico',
    'FM': 'Micronesia (Federated States of)',
    'MD': 'Moldova (Republic of)',
    'MC': 'Monaco',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MS': 'Montserrat',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NR': 'Nauru',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NC': 'New Caledonia',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NU': 'Niue',
    'NF': 'Norfolk Island',
    'MP': 'Northern Mariana Islands',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palau',
    'PS': 'Palestine, State of',
    'PA': 'Panama',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PN': 'Pitcairn',
    'PL': 'Poland',
    'PT': 'Portugal',
    'PR': 'Puerto Rico',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RU': 'Russian Federation',
    'RW': 'Rwanda',
    'BL': 'Saint Barthélemy',
    'SH': 'Saint Helena, Ascension and Tristan da Cunha',
    'KN': 'Saint Kitts and Nevis',
    'LC': 'Saint Lucia',
    'MF': 'Saint Martin (French part)',
    'PM': 'Saint Pierre and Miquelon',
    'VC': 'Saint Vincent and the Grenadines',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'ST': 'Sao Tome and Principe',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapore',
    'SX': 'Sint Maarten (Dutch part)',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'SB': 'Solomon Islands',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'GS': 'South Georgia and the South Sandwich Islands',
    'SS': 'South Sudan',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'SJ': 'Svalbard and Jan Mayen',
    'SZ': 'Swaziland',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'SY': 'Syrian Arab Republic',
    'TW': 'Taiwan, Province of China',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania, United Republic of',
    'TH': 'Thailand',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TK': 'Tokelau',
    'TO': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'TN': 'Tunisia',
    'TR': 'Turkey',
    'TM': 'Turkmenistan',
    'TC': 'Turks and Caicos Islands',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom of Great Britain and Northern Ireland',
    'US': 'United States of America',
    'UM': 'United States Minor Outlying Islands',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VU': 'Vanuatu',
    'VE': 'Venezuela (Bolivarian Republic of)',
    'VN': 'Viet Nam',
    'VG': 'Virgin Islands (British)',
    'VI': 'Virgin Islands (U.S.)',
    'WF': 'Wallis and Futuna',
    'EH': 'Western Sahara',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
};

export function wuCountryCodeToName (wuCode) {
    let isoCode = isoCodes[wuCode];
    return countryNames[isoCode];
}
